config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'profile/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :posts do
    member do
      patch :upvote
      patch :downvote
    end
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :profiles, only: [:show]


  root 'welcome#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true  # Permitir que el usuario sea opcional (para comentarios de "invitado")
  attribute :display_name, :string

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # POST /comments or /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
  
    if user_signed_in?
      @comment.user = current_user
    else
      @comment.display_name = params[:comment][:display_name]
    end
  
    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      redirect_to @post, alert: 'Failed to create comment.'
    end
  end

  # GET /comments/1/edit
  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post), notice: 'Comentario actualizado correctamente.'
    else
      redirect_to post_path(@comment.post), alert: 'Comentario no se pudo actualizar'
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    if @comment.destroy
      redirect_to post_path(@comment.post), notice: 'Comentario eliminado correctamente.'
    else
      return
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def authorize_comment_owner!(comment)
      unless user_signed_in? && (comment.user == current_user) ||  current_user.admin? 
        # Verifica si el usuario no está autenticado pero es el autor del comentario
        unless !user_signed_in? && comment.user.nil?
          redirect_to post_path(comment.post), alert: 'No tienes permiso para realizar esta acción.'
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      permitted_params = [:content, :post_id]
      permitted_params << :display_name unless user_signed_in?
      params.require(:comment).permit(permitted_params)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<div class="styled-form post-form">
<%= form_with(model: [post, comment], url: post_comment_path(@post, comment), method: :patch) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field-standar">
    <%= form.label :Mensaje, style: "display: block" %>
    <%= form.text_area :content, class: "form-input-standar" %>
  </div>

  <% unless user_signed_in? %>
    <div>
      <%= form.label :display_name, style: "display: block" %>
      <%= form.text_field :display_name, class: "form-input-standar" %>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :post_id %>
  </div>

  <div class="form-actions">
    <%= form.submit "Enviar", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/comments/edit.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="center-text mb-5">Editar comentario</h1>

<%= render 'form', comment: @comment, post: @post %>


<br>

<div class="back-links">
  <%= link_to "Volver atrás", request.referer, class: "back-link" %>
  <%= link_to "Volver a Feed", posts_path, class: "feed-link" %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comentarios</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>



<%= render @comment %>

<div>
  <%= link_to "Editar", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= link_to "Eliminar este comentario", post_comment_path(@post, comment), method: :delete, data: { confirm: "¿Estás seguro de eliminar este comentario?" } %>

</div>