config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'profile/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :posts do
    member do
      patch :upvote
      patch :downvote
    end
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :profiles, only: [:show]


  root 'welcome#index'
end

app/views/shared/_footer.html.erb
<footer class="bg-footer">
    <div class="container mb-0 py-4 text-center">
        <p class=" pt-1 text-white">Derechos Reservados Crazy4Cats</p>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-nav p-4">
    <div class="container-fluid">
        <a class="navbar-brand custom-logo" href="/">
        <%= image_tag("logocat.png", alt: "Crazy4Cats Logo", class: "logo-image") %>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                    <%= link_to "MiauFeed", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= profile_index_path %>">MishiPerfil</a>
            </li>
        </ul>
        <ul class="navbar-nav ms-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="far fa-bell d-none d-md-block" style="font-size: 22px; color: #CBE4F2;"></i>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= image_tag("avatar.png", alt: "avatar", class: "rounded-circle", width: "40px", height: "40px") %>
                </a>
                <ul class="dropdown-menu dropdown-menu-end text-left px-3">
                <li><span class="dropdown-item"><%= current_user.username %></span></li>
                <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Editar Datos</a></li>
                <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                </ul>
            </li>
            <% else %>
            <li class="nav-item">
                <a class="nav-link btn btn-outline-warning" href="<%= new_user_session_path %>">Iniciar Sesión</a>
            </li>
            <% end %>
        </ul>
        </div>
    </div>
</nav>