config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'profile/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :posts do
    member do
      patch :upvote
      patch :downvote
    end
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :profiles, only: [:show]


  root 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title_and_username,
                  against: [:title],
                  associated_against: {
                    user: [:username]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images

  acts_as_votable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    @posts = Post.all.order(created_at: :desc)

    @pagy, @posts = pagy(@posts) # Gema pagy

    @filtro = params[:buscar] # Gema pg-search
    if @filtro.present?
      @posts = Post.search_by_title_and_username(@filtro)
    end
  end


  # Dar Me gusta
  def upvote
    if current_user.voted_up_on? @post
      @post.unvote_by current_user
    else
      @post.upvote_by current_user
    end

    respond_to do |format|
      format.html do
        redirect_to @post
      end
      format.js do
        render "vote.js.erb" # Renderiza la vista parcial para actualizar los botones y el recuento
      end
    end
  end

  # Dar No me gusta
  def downvote
    if current_user.voted_down_on? @post
      @post.unvote_by current_user
    else
      @post.downvote_by current_user
    end

    respond_to do |format|
      format.html do
        redirect_to @post
      end
      format.js do
        render "vote.js.erb" # Renderiza la vista parcial para actualizar los botones y el recuento
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to @post, notice: 'Post actualizado correctamente.'
    else
      render :edit
    end
  end


  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    
      if current_user.admin?
        @post.destroy
        redirect_to root_path, notice: 'Post eliminado correctamente.'
      elsif current_user == @post.user
        @post.destroy
        redirect_to root_path, notice: 'Post eliminado correctamente.'
      else
        redirect_to root_path, alert: 'No tienes permiso para eliminar este post.'
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, images: [])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_downvote_link.html.erb
<%= content_tag "div", id: "downvote-#{post.id}" do %>
    <%= link_to downvote_post_path(post), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
        <% if current_user.voted_up_on? post %>
        <i class="fas fa-thumbs-down"></i>
        No me gusta
        <% else %>
        <i class="far fa-thumbs-down"></i>
        No me gusta
        <% end %>
    <% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="styled-form post-form">
  <%= form_with(model: post, local: true, class: "custom-form") do |form| %>
    <% if post.errors.any? %>
      <div class="error-messages">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-input" %>
    </div>

    <div class="form-field">
      <%= form.label :content %>
      <%= form.text_area :content, class: "form-input" %>
    </div>

    <% if post.images.attached? %>
      <h5>Imágenes existentes:</h5>
      <div class="image-list">
        <% post.images.each do |image| %>
          <%= image_tag image, class: "img-fluid" %>
        <% end %>
      </div>
    <% else %>
      <div class="form-field">
        <%= form.label :images, "Cargar Imágenes" %>
        <%= form.file_field :images, class: "form-input", multiple: true %>
      </div>
    <% end %>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="form-actions">
      <%= form.submit "Enviar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

app/views/posts/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{post.id}" do %>
    <%= link_to upvote_post_path(post), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
        <% if current_user.voted_up_on? post %>
        <i class="fas fa-thumbs-up"></i>
        Ya no me gusta
        <% else %>
        <i class="far fa-thumbs-up"></i>
        Me gusta
        <% end %>
    <% end %>
<% end %>

app/views/posts/_votes_down.html.erb
<%= content_tag "div", id: "votes_down-#{post.id}" do %>
    <%= post.cached_votes_down %>
<% end %>

app/views/posts/_votes_up.html.erb
<%= content_tag "div", id: "votes_up-#{post.id}" do %>
    <%= post.cached_votes_up %>
<% end %>

app/views/posts/edit.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="center-text mb-5">Editar Post</h1>

<%= render "form", post: @post %>

<br>

<div class="back-links">
  <%= link_to "Volver atrás", request.referer, class: "back-link" %>
  <%= link_to "Volver a Feed", posts_path, class: "feed-link" %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<!--Grilla con 3 columnas-->
  <div class="container">
        <div class="row">
<!---Columna Izquierda-->
    <% if user_signed_in? %>
    <div class="col-12 col-lg-3 pt-5 pe-5">
      <div class="card mb-4" >
        <%= image_tag("cat1", class:"d-block w-100 img-fluid") %>
          <div class="card-body text-center ">
            <h5 class="card-title">Gatuno Fashion</h5>
            <p class="card-text text-justify mb-2">I wish i was a little bit taller, wish i was a baller, wish i had a girl… also.</p>
            <ul class="list-unstyled nav justify-content-center">
              <a href="#" class="text-dark text-decoration-none"> <li class="nav-item">Amigos <br> <strong>12M</strong></li></a>
              <a href="#" class="text-dark text-decoration-none"> <li class="nav-item">Enemigos <br> <strong>1</strong></li></a> 
            </ul>
            </div>
      </div>


      <div class="card mb-4">
        <div class="card-body">
          <h5 class="mb-3 card-title">Sobre ti</h5>
          <p class="card-text"> <i class="fas fa-calendar-week mr-2"></i> Mascota de<a href="#" class="text-decoration-none"> tu gato</a></p>
          <p class="card-text"> <i class="fas fa-user-friends mr-2"></i> Amistad con <a href="#" class="text-decoration-none">obama</a></p>
          <p class="card-text"> <i class="far fa-building mr-2"></i> Trabajo en <a href="#" class="text-decoration-none">Github</a></p>
          <p class="card-text"> <i class="fas fa-home mr-2"></i> Vivo en <a href="#" class="text-decoration-none">Mi casa</a></p>
          <p class="card-text"> <i class="fas fa-map-marker mr-2"></i> De <a href="#" class="text-decoration-none">Santiago,Chile</a></p>
        </div>
      </div>

      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Tus Fotos</h5>
          <div class="row">
            <div class="col-6 p-1">
              <%= image_tag("cat1", class:"d-block w-100 img-fluid") %>
              <%= image_tag("cat1", class:"d-block w-100 img-fluid") %>
              <%= image_tag("cat1", class:"d-block w-100 img-fluid") %>
            </div>
                                
            <div class="col-6 p-1">
              <%= image_tag("cat1", class:"d-block w-100 img-fluid") %>
              <%= image_tag("cat1", class:"d-block w-100 img-fluid") %>
              <%= image_tag("cat1", class:"d-block w-100 img-fluid") %>
            </div>

              </div>
            </div>
          </div>
        </div>
        <% else %>
        <div class="col-12 col-lg-3 pt-5 pe-5">
            <!-- Contenido para usuarios no logueados -->
            <div class="card mb-4">
              <div class="card-body">
                <h6 class="card-title">Rayban ft. Mishis</h6>
                <%= image_tag("cat9", class:"d-block w-100 img-fluid") %>
                  <h6 class="py-3">Si no come zanahoria, no tiene vista de conejo</h6>
                  <p class="card-text text-justify">Prueba los nuevos Mishi Glasses con el puro estilo del gato Benito.</p>
                <a href="#" class="btn btn-outline-info card-link btn-sm">Cómpralos ya!</a>
              </div>
            </div>
          </div>
        <% end %>

<!--Fin de Columna Izquierda-->


<!--Columna media-->
<div class="col-12 col-lg-6 align-content-center">
    <div class="center-text">
      <h1>MishisPosts</h1>
    </div>


      
      <!--Barra de búsqueda Gem pg-search -->
      <%= form_with url: posts_path, method: :get do |form| %> <!-- Gema search -->
  <!-- Cuadro de búsqueda de posts anteriores -->
        <div class="card mb-2">
          <div class="card-body">
            <div class="input-group">
              <%= form.text_field :buscar, class: "form-control buscar", placeholder: "Buscar posts anteriores", value: @filtro %>
              <div class="input-group-append">
                <%= form.button type: :submit, class: "btn btn-outline-primary" do %>
                  <i class="fas fa-camera"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <!--Botón Nuevo Post-->
      <div>
        <% if user_signed_in? %>
          <%= link_to "Nuevo Post", new_post_path, class: "btn btn-gradient mb-5" %>
        <% else %>
          <%= link_to "Ingresa a tu sesión para Mishipostear", new_user_session_path, class: "btn btn-gradient mb-5" %>
        <% end %>
      </div>

      <!--Gem pg-search-->
      <%== pagy_bootstrap_nav(@pagy) %>
      <!-- Posts -->
      <div id="posts" class="center-content">
        <% @posts.each do |post| %>
          <div class="col-12 col-lg-6">
            <div class="middle-column">
              <div class="card wider-card">
                <div class="card-header bg-transparent">
                <!-- Agregar el nombre del usuario y su avatar -->
                  <div class="user-info pb-3">
                    <div class="user-avatar">
                      <%= image_tag 'avatar.png', class: 'avatar-image' %>
                    </div>
                    <div class="user-name">
                      Publicado por <%= post.user&.username || 'Usuario Desconocido' %>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <% if post.images.attached? %>
                    <div class="post-images">
                      <% post.images.each do |image| %>
                    <%= link_to post_path(post) do %>
                      <%= image_tag image, class: 'card-img-top', style: 'width: 600px; height: auto;' %>
                    <% end %>
                  <% end %>
                    </div>
                  <% end %>
                  <h2 class="card-title pt-5"><%= post.title %></h2>
                  <p class="small-title"><%= post.content %></p>
                  <hr class="post-divider">


                  <!-- Renderizar los enlaces de votación usando los botones -->
                  <div class="voting-buttons">
                    <%= button_to upvote_post_path(post), method: :patch, remote: true, data: { disable_with: "voting..." }, class: "btn btn-primary like-btn" do %>
                      <i class="fas fa-thumbs-up"></i>
                      <span class="vote-count"><%= post.cached_votes_up %></span>
                    <% end %>

                    <%= button_to downvote_post_path(post), method: :patch, remote: true, data: { disable_with: "voting..." }, class: "btn btn-danger dislike-btn" do %>
                      <i class="fas fa-thumbs-down"></i>
                      <span class="vote-count"><%= post.cached_votes_down %></span>
                    <% end %>
                  </div>

                  <%= link_to 'Ver Comentarios', post %>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <!--Gem pg-search-->
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    
<!--Fin columna Posts-->

<!---Columna Derecha----->
        
  <div class="col-12 col-lg-3 pt-5 ps-5">

        <div class="card mb-4" >
            <div class="card-body">
                <h6 class="card-title">Viaje + Hotel Gatuno</h6>
                <p class="card-text text-justify"> <span class="h6">Es tiempo de visitar París.</span> París para relajarse, comer y gatos en el Louvre. Además oímos que la gente es cool allá. Qué estás esperando?</p>
                <a href="#" class="btn btn-outline-info card-link btn-sm">Comprar ticket</a>
            </div>
        </div>


        <div class="card shadow-sm mb-4">
            <div class="card-body">
              <h6 class="card-title ">Te podría gustar</h6>
              <p>GatoBenito @benitogarrita</p>
              <a href="#" class="btn btn-outline-info btn-sm mb-3"><i class="fas fa-user-friends"></i>Seguir</a>
              <p>Don Gato y su Pandilla @DonGato</p>
              <a href="#" class="btn btn-outline-info  btn-sm"><i class="fas fa-user-friends"></i>Seguir</a>
            </div>
            <div class="card-footer">
                <p class="lead" style="font-size:16px;">Félix de verdad adora a estos nerds, nadie sabe por qué.</p>
            </div>
        </div>

        <div class="card shadow-sm">
            <div class="card-body">
                <p>&copy; 2023 Crazy4Cats
                        <a href="#">About</a>
                        <a href="#">Help</a>
                        <a href="#">Terms</a>
                        <a href="#">Privacy</a>
                        <a href="#">Cookies</a>
                        <a href="#">Ads </a>
                        <a href="#">Info</a>
                        <a href="#">Brand</a>
                        <a href="#">Blog</a>
                        <a href="#">Status</a>
                        <a href="#">Apps</a>
                        <a href="#">Jobs</a>
                        <a href="#">Advertise</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p class="error-message"><%= flash[:error] %></p>

<div class="post-container">
  <h1><%= @post.title %></h1>

  <% if @post.images.attached? %>
    <div class="post-images">
      <% @post.images.each do |image| %>
        <%= image_tag image, class: 'img-fluid' %>
      <% end %>
    </div>
  <% end %>
  <div class="edit-delete-links pt-5">
  <% if user_signed_in? && (current_user == @post.user || current_user.admin?) %>
    <%= link_to "Editar", edit_post_path(@post), class: "edit-link"  %>
    <%= button_to "Eliminar", @post, method: :delete, data: { confirm: "¿Estás seguro de eliminar este post?" }, class: "delete-button" %>
  <% end %>
  </div>

  <p><%= @post.content %></p>
  <div class="user-info">
    Publicado por <%= @post.user.username %> , <%= @post.created_at.strftime('%d de %B de %Y') %>
  </div>

  <hr class="post-divider">
  <div class="voting-buttons">
    <%= button_to upvote_post_path(@post), method: :patch, remote: true, data: { disable_with: "voting..." }, class: "btn btn-primary like-btn" do %>
      <i class="fas fa-thumbs-up"></i>
      <span><%= @post.cached_votes_up %></span>
    <% end %>

    <%= button_to downvote_post_path(@post), method: :patch, remote: true, data: { disable_with: "voting..." }, class: "btn btn-danger dislike-btn" do %>
      <i class="fas fa-thumbs-down"></i>
      <span><%= @post.cached_votes_down %></span>
    <% end %>
  </div>


<!-- Comentarios -->
<div class="comments-section">
  <% @comments.each do |comment| %>
    <div class="comment">
    <p class="comment-time"><%= comment.created_at.strftime('%H:%M %p') %></p>
      <div class="user-info">
        <%= image_tag("avatar", class: "rounded-circle", style: "width:6%") %>
        <strong>
          <%= comment.user ? comment.user.username : 'Guest' %>
        </strong>
        <div class="comment-content">
          <p><%= comment.content %></p>
          <% if user_signed_in? && (current_user == comment.user || current_user.admin?) %>
            <div class="edit-delete-links">
              <%= link_to "Editar", edit_post_comment_path(@post, comment), class: "edit-link" %>
              <%= button_to "Eliminar", post_comment_path(comment.post, comment), method: :delete, data: { confirm: "¿Estás seguro de eliminar este comentario?" }, class: "delete-button" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>



    <div class="comment-form">
      <%= form_for [@post, @comment] do |f| %>
        <%= f.text_area :content, placeholder: 'Escribe tu comentario...' %><br>
        <%= f.submit 'Agregar comentario', class: "btn btn-gradient" %>
      <% end %>
    </div>
  </div>

    <div class="feed-link-container">
    <%= link_to "Volver atrás", :back, class: "back-link" %>
    <%= link_to "Volver Feed", posts_path, class: "feed" %>
    </div>

app/views/posts/vote.js.erb
document.getElementById("upvote-<%= @post.id %>").innerHTML = "<%= j render "posts/upvote_link", post: @post %>";
document.getElementById("downvote-<%= @post.id %>").innerHTML = "<%= j render "posts/downvote_link", post: @post %>";
document.getElementById("votes_up-<%= @post.id %>").innerHTML = "<%= j render "posts/votes_up", post: @post %>";
document.getElementById("votes_down-<%= @post.id %>").innerHTML = "<%= j render "posts/votes_down", post: @post %>";